# Use postgres/password user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: mutillidae
  mutillidae:
    image: korius/mutillidae-no-db
    ports:
      - 8083:80
      - 8483:443

